# Generated by Django 3.2 on 2023-07-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, null=True)),
                ('name', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'dict',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dict_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'dict_type',
                'managed': False,
            },
        ),
    ]
